Imagination_General:
  env : "SimplePickup"
  max_ep_len : 20
  encoder_model : "all-MiniLM-L12-v2"
  datapath : "data"
  vae_checkpoint : "models/parted_vae/parted_vae_15000.pth"
  sentece_encoder_model : "models/captioner.pth"
  buffer_size : 3000_00
  agent : 'sac'
  agent_checkpoint : "models/sac_agent/SAC_discrete.tar"
  num_goals : 2
  captioner_hidden_dim : 768
  captioner_path : "models/captioner.pth"

Imagination_Network:
  lr : 0.0001
  batch_size: 500
  hidden_layers : [512]
  epoch : 5000
  max_gradient : 10
  checkpoint_interval : 200
  feature_dim : 64
  lstm_hidden_size : 512