General:
  env : "SimplePickup"
  max_ep_len : 20
  encoder_model : "all-MiniLM-L12-v2"
  datapath : "data"
  vae_checkpoint : "models/all-MiniLM-L12-v2/Feature_based/vae_normal.pth"
  buffer_size : 3000_00
  agent : 'sac'
  agent_checkpoint : "models/sac_agent/SAC_discrete.tar"

Network:
  lr : 0.001
  batch_size: 1000
  hidden_layers : [256, 256, 512, 512, 512]
  epoch : 80000
  max_gradient : 10
  checkpoint_interval : 200