M2_General:
  env : "SimplePickup"
  agent_view_size : 3
  load_model_path : 'models/'
  datapath : "data"
  num_goals : 2
M2_Network:
  input_dim : 3
  encoder_hidden_dim : [512]
  latent_dim : 24
  decoder_hidden_dim : [512]
  epochs : 800
  batch_size : 64
  lr_model : 1e-4