M2_General:
  env : "SimplePickup"
  agent_view_size : 3
  load_model_path : 'models/'
  datapath : "data"
  y_dim : 3
  human_label_ratio : 0.20
M2_Network:
  input_dim : 85
  classifier_hidden_dim : [512,512]
  feature_encoder_hidden : [512,512]
  h_dim : 128 
  latent_dim : 16
  decoder_hidden_dim : [512]
  epochs : 2000
  batch_size : 64
  lr_model : 5e-4
  kl_weight_start : 0.01
  kl_weight_end : 0.05
  save_freequency : 100
  label_loss_weight : 10
  recon_loss_weight : 1