General:
  env : "SimplePickup"
  use_logger : true
  encoder_model : "all-MiniLM-L12-v2"
  datapath : "data"
  num_goals : 2
VAE_Network:
  lr : 0.0001
  batch_size: 1000
  encoder_hidden : [128,256,64]
  encoder_out : 32
  latent_dim : 12
  decoder_hidden : [256]
  epoch : 80000
  max_gradient : 10